### PR TITLE
Use a single thread loop to delete expired items

### PR DESCRIPTION
**Pull request by dariogriffo**
Moving the delete expired items into a single thread.
Changing the example to be a .net worker service to allow IHostApplicationLifetime available and use DI all the way down in the example.

### CODE REVIEW

**Comment by leonibr** [comment]
First of all, thank you for your pull request! I will review it later today

**Comment by dariogriffo** [comment]
> First of all, thank you for your pull request! I will review it later today

Thanks a lot! I want to start using this package and would be great to improve the deleting loop.

**Comment by dariogriffo** [comment]
I did some code cleanup (sealed and internal classes), separated the responsibilities for each class, using DI in each class

**Comment by leonibr** [comment]
I will update the docs because this release will be a breaking change release

**Pull request merged**
